### ISSUE TITLE
Add support for Elm custom types

### ISSUE THREAD

**Issue by berry** [dillonkearns/elm-typescript-interop#14]
I am currently doing an authentication interop between Elm and Amplify (a JS library for AWS). Elm-typescript-interop is great and a lot easier and quicker than doing brittle messaging stuff that depends on string interpretations.

Authentication consists of a series of stages. I use a custom type:

```Elm
type LoginStatus
    = NotLoggedIn
    | NewPasswordRequired
    | LoggedIn
    | LoggedOut
    | ChangePasswordRequest
    | ChangePasswordRequestComplete
    | ForgotPasswordRequest
    | ForgotPasswordRequestVerificationCodeComplete
    | ForgotPasswordRequestComplete
```

I would love elm-typescript-interop to support this type of custom type and translate it on Typescript side to Typescript enum's. This would help me a lot to keep the same information model on Elm side and on Typescript side in sync. 

Of course Elm allows custom types to associate data to variants. I do not know how that would translate to Typescript.

Thank you,
Berry

**Comment by dillonkearns** [comment]
Hello Berry, thanks for the request.

Representing this in TypeScript is actually very doable (see the Discriminated Unions section [in this post](https://www.typescriptlang.org/docs/handbook/advanced-types.html)).

The problem is that you can't pass Elm Union Types (now called Custom Types) through ports. Generating the TypeScript declarations for primitive types (Strings, records, etc.) is much simpler because you can annotate your ports as sending those exact values. Creating typescript declarations for Elm Custom Type through ports presents a few challenges:

1. How do you now guarantee that the type you are passing is of the Custom Type (e.g. `LoginStatus`)? You could have the type of your port be a `Json.Encode.Value`, but then how can you prove to `elm-typescript-interop` that you will only pass data that represents that Custom Type?
2. How do you encode/decode that custom type? This now requires generating some Elm code. Generating the code isn't difficult, but coming up with an intuitive and simple way for the users of this library is. And again, how do you prove to `elm-typescript-interop` that these encoders/decoders are being used so it can know it is of type `LoginStatus`, for example?

I'm totally open to discussing these ideas, but I don't want to tackle anything unless we can find a really solid approach that is both robust and intuitive/simple.

**Comment by frankdugan3** [comment]
I can't think of anything other than using comments on Elm's side to indicate the JSON field should be a custom type... Not very elegant, but it could be pretty straightforward to use.

Perhaps the init function could be scanned to see if decoders are being used on flags. The issue in that case would be a chicken-and-egg of not having the generated decoders.

**Comment by ogreyard** [comment]
@dillonkearns one question regarding custom types. Is it true they lead to an "unknown" data type in the index.d.ts? That's what I am currently struggling with, as it causes compile errors when I am calling such a function with "unknown" data type with any typescript type. What I do is replace the "unknown" with any in the index.d.ts. Admittedly not nice, but at least does not yield any compile errors and allows to still use `elm-typescript-interop`.
In case this is expected behaviour, would it make sense to change that to "any" type instead of "unknown" as a default for custom/unsupported types?

**Comment by pravdomil** [comment]
I've created library for encoding/decoding custom types into/from json https://github.com/pravdomil/elm-json-interop can somebody try it?

**Comment by dillonkearns** [comment]
I built a solution for this in the `elm-ts-interop` package (that's the new approach to this problem, see #36 discussing why I'm deprecating `elm-typescript-interop` in favor of this new package). I'm really pleased with the new solution, hope everyone enjoys using it!
