### ISSUE TITLE
Parse failure

### ISSUE THREAD

**Issue by sporto** [dillonkearns/elm-typescript-interop#9]
Hi
I tried to run this but got what appears to be a parsing failure.
I have pasted the output here https://paste.ee/p/TvYVi

The project I used is available here https://github.com/sporto/save-up/tree/master/client

Thanks

**Comment by dillonkearns** [comment]
Hey @sporto, thank you for reporting the issue! It turns out your project still has an `elm-package.json` file, and the logic I had was checking for `elm-package.json` before `elm.json`. It's working now!

https://github.com/dillonkearns/elm-typescript-interop/blob/master/CHANGELOG.md#007---2018-09-13

**Comment by sporto** [comment]
Hi Dillon

Unfortunately this didn't fix the issue for me. I removed `elm-package` and update this node module. Then ran again. I see this https://paste.ee/p/TbTtw

Thanks

**Comment by dillonkearns** [comment]
Hey @sporto, that's interesting, it works for me in my cloned version of the code.

It appears that the error you're encountering is happening because it's finding the module `Test.Basics`, which I see in the `node_modules` folder in my cloned down repo after I `npm install`. I'm not sure why your version would be looking in that directory, though, since [the only `source-directory` you have listed is "src"](https://github.com/sporto/save-up/blob/master/client/elm.json#L3-L5).

For reference, here's the path where I see it:
`save-up/client/node_modules/elm-webpack-loader/test/fixtures/elm-stuff/packages/elm-lang/core/5.0.0/tests/Test/Basics.elm`

Can you do an `ls` of your `client/src` folder for me so I can see if there is either an `elm-stuff` or a `node_modules` folder (or any other directories that are in the `.gitignore` and contain `.elm` files).

I'm trying to figure out how to have it ignore folders like `elm-stuff` and `node_modules` when it's scanning through those folders.

**Comment by dillonkearns** [comment]
I just pushed a new version that will have better error messages for `elm-ast` parsing errors, as well. Hopefully that makes it a little easier to debug the issue.

For reference, the reason it is getting syntax errors on those files is because there are some bugs with the elm-ast packages out there. I just switched over from `Bogdanp/elm-ast` to `tunguski/elm-ast` because the Bogdanp one had some pretty basic errors that tunguski seemed to fix (for example, it was failing to parse when there were comments within function bodies). But certain files that have really gnarly syntax it seems to fail to parse still.

**Comment by sporto** [comment]
I had a folder `elm-stuff` inside `src`. Probably created when using the repl in Elm 0.18. After deleting this folder it worked.

Thanks for the help

**Comment by dillonkearns** [comment]
Yeah, that makes perfect sense. I definitely want the CLI to be robust enough to "just work". I went ahead and published a new version that ignores any folders within the `source-directories` that are named either `elm-stuff` or `node_modules`.

Thanks for reporting all the details, that's super helpful 👍
